LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := gnuobjc_static
LOCAL_SRC_FILES := libs/$(TARGET_ARCH_ABI)/$(TARGET_TOOLCHAIN_VERSION)/libgnuobjc_static.a
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include/$(TARGET_TOOLCHAIN_VERSION)
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := gnuobjc_shared
LOCAL_SRC_FILES := libs/$(TARGET_ARCH_ABI)/$(TARGET_TOOLCHAIN_VERSION)/libgnuobjc_shared.so
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)/include/$(TARGET_TOOLCHAIN_VERSION)
include $(PREBUILT_SHARED_LIBRARY)
