/* WARNING!!! THIS IS AUTO-GENERATED FILE!!! DO NOT MODIFY IT MANUALLY!!! */
/* GENERATED BY: $CRYSTAX/bin/gen-bsd-sources  */

/*
 * CrystaX NDK contains code from libc library of FreeBSD project which by-turn contains
 * code from other projects. Also, several another open-source projects used, such as GNU gcc,
 * GNU binutils, LLVM clang, LLVM libc++ etc. To see specific authors and/or licenses, look
 * into appropriate source file. Here is license for those parts which are not derived from
 * any other projects but written by CrystaX.
 *
 * Copyright (c) 2011-2015 CrystaX.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification, are
 * permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright notice, this list of
 *       conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright notice, this list
 *       of conditions and the following disclaimer in the documentation and/or other materials
 *       provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY CrystaX ''AS IS'' AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL CrystaX OR
 * CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
 * NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
 * ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * The views and conclusions contained in the software and documentation are those of the
 * authors and should not be interpreted as representing official policies, either expressed
 * or implied, of CrystaX.
 */

#ifndef __CRYSTAX_INCLUDE_7C0B10E49EA79B9702A98AC7E13A0F3BB1C590B827F29457EF15E41C512CC259
#define __CRYSTAX_INCLUDE_7C0B10E49EA79B9702A98AC7E13A0F3BB1C590B827F29457EF15E41C512CC259

#include <crystax/id.h>
#include <crystax/freebsd.h>

#include <crystax/freebsd/sys/sys/mangled-queue.h>

#endif /* __CRYSTAX_INCLUDE_7C0B10E49EA79B9702A98AC7E13A0F3BB1C590B827F29457EF15E41C512CC259 */
